package cz.ctuprotebe.vyletnikviz;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
 static final String ENDPOINT="https://vyletni-kviz-api.daniel-pohl.chatgpt.site/generate";
 static final String[] CATS={"Česko","Svět","Historie","Zeměpis","Příroda","Věda a technika","Kultura","Film a televize","Hudba","Sport","Český jazyk","Gastronomie","Zajímavosti"};
 final int NAVY=Color.rgb(25,50,74),RED=Color.rgb(217,45,58),PINK=Color.rgb(179,60,134),BLUE=Color.rgb(38,119,168),GREEN=Color.rgb(32,132,92),GOLD=Color.rgb(190,132,22),SOFT=Color.rgb(241,245,248);
 LinearLayout root,answers; SharedPreferences prefs; ToneGenerator tones;
 ArrayList<Question> quiz=new ArrayList<>(); ArrayList<Player> players=new ArrayList<>(); Config cfg; State game;
 ArrayDeque<State> undo=new ArrayDeque<>(),redo=new ArrayDeque<>();

 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("quiz",MODE_PRIVATE);tones=new ToneGenerator(AudioManager.STREAM_MUSIC,70);home();}
 protected void onDestroy(){tones.release();super.onDestroy();}
 TextView tv(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(23,33,43));v.setPadding(12,10,12,10);if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setAllCaps(false);b.setMinHeight(54);return b;}
 EditText edit(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(17);return e;}
 Spinner spin(String... a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
 void base(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(26,28,26,42);s.addView(root);setContentView(s);}
 void title(String a,String b){TextView h=tv(a,29,true);h.setTextColor(NAVY);root.addView(h);if(b!=null)root.addView(tv(b,16,false));}
 void section(String s){TextView h=tv(s,20,true);h.setTextColor(NAVY);h.setPadding(8,24,8,8);root.addView(h);}
 String today(){return new SimpleDateFormat("dd. MM. yyyy",Locale.forLanguageTag("cs-CZ")).format(new Date());}
 String num(double x){return Math.abs(x-Math.rint(x))<.001?String.valueOf((int)Math.rint(x)):String.format(Locale.forLanguageTag("cs-CZ"),"%.1f",x);}

 void home(){base();title("VÝLETNÍ KVÍZ","Kvízy, které se promění ve vzpomínky na společné výlety.");Button n=btn("Nový výletní kvíz");n.setOnClickListener(v->setup());root.addView(n);Button q=btn("Rychlá hra: Barča × Dominik");q.setOnClickListener(v->quick());root.addView(q);Button h=btn("Kronika výletů");h.setOnClickListener(v->history());root.addView(h);Button s=btn("Dlouhodobá tabulka hráčů");s.setOnClickListener(v->stats());root.addView(s);Button c=btn("Nastavení AI připojení");c.setOnClickListener(v->connection());root.addView(c);root.addView(tv("Aplikace sama hlídá pořadí, přebírání otázek i bodování. Celý kvíz se uloží předem a na výletě funguje offline.",14,false));}
 void quick(){cfg=new Config();cfg.title="Rychlý kvíz";cfg.date=today();players.clear();players.add(new Player("Barča","Psychologie",PINK));players.add(new Player("Dominik","Lední hokej",BLUE));loadAsset();start();}

 void setup(){base();title("NOVÝ VÝLET","Nejdřív vzpomínka, potom hráči a pravidla.");section("Výlet");EditText trip=edit("Název, například Okoř","Výlet");root.addView(trip);EditText date=edit("Datum",today());root.addView(date);EditText note=edit("Poznámka nebo hláška z výletu","");root.addView(note);
  section("Hráči v pořadí");LinearLayout holder=new LinearLayout(this);holder.setOrientation(LinearLayout.VERTICAL);root.addView(holder);ArrayList<EditText[]> rows=new ArrayList<>();String[][] saved=profiles();if(saved.length<2)saved=new String[][]{{"Barča","Psychologie"},{"Dominik","Lední hokej"}};for(int i=0;i<Math.min(5,saved.length);i++)playerRow(holder,rows,saved[i][0],saved[i][1]);Button add=btn("+ Přidat hráče");add.setOnClickListener(v->{if(rows.size()<5)playerRow(holder,rows,"","");else toast("Maximum je 5 hráčů");});root.addView(add);
  section("Délka a obtížnost");Spinner count=spin("10 otázek","20 otázek","30 otázek","40 otázek");root.addView(count);Spinner diff=spin("Vyvážená","Pohodová","Náročná");root.addView(diff);
  section("Okruhy");ArrayList<CheckBox> boxes=new ArrayList<>();for(String c:CATS){CheckBox x=new CheckBox(this);x.setText(c);x.setTextSize(16);x.setChecked(Arrays.asList("Česko","Svět","Historie","Příroda","Věda a technika","Kultura","Zajímavosti").contains(c));boxes.add(x);root.addView(x);}
  section("Herní módy");CheckBox bizarre=check("Bizarní svět – pravdivé a podivné otázky",true);root.addView(bizarre);Spinner be=spin("Každých 5 otázek","Každých 8 otázek","Jednou za hru");root.addView(be);CheckBox strong=check("Silné okruhy jednotlivých hráčů",true);root.addView(strong);Spinner se=spin("Každá 3. osobní otázka","Každá 4. osobní otázka","Jednou za hru");root.addView(se);CheckBox sound=check("Zvuky a jemné vibrace",prefs.getBoolean("sound",true));root.addView(sound);
  Button off=btn("Připravit offline kvíz");off.setOnClickListener(v->{if(collect(rows,boxes,trip,date,note,count,diff,bizarre,be,strong,se,sound)){loadAsset();trim(cfg.count);start();}});root.addView(off);Button ai=btn("Vygenerovat nový kvíz s AI");ai.setOnClickListener(v->{if(collect(rows,boxes,trip,date,note,count,diff,bizarre,be,strong,se,sound))generate(ai);});root.addView(ai);Button back=btn("Zpět");back.setOnClickListener(v->home());root.addView(back);
 }
 CheckBox check(String s,boolean on){CheckBox c=new CheckBox(this);c.setText(s);c.setTextSize(16);c.setChecked(on);return c;}
 void playerRow(LinearLayout holder,ArrayList<EditText[]> rows,String name,String topic){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(10,8,10,8);card.setBackgroundColor(SOFT);EditText n=edit("Jméno hráče",name),t=edit("Silný okruh, například lední hokej",topic);card.addView(n);card.addView(t);Button del=btn("Odebrat hráče");del.setOnClickListener(v->{if(rows.size()<=2){toast("Musí zůstat alespoň 2 hráči");return;}int i=holder.indexOfChild(card);holder.removeView(card);rows.remove(i);});card.addView(del);holder.addView(card);rows.add(new EditText[]{n,t});}
 boolean collect(ArrayList<EditText[]> rows,ArrayList<CheckBox> boxes,EditText trip,EditText date,EditText note,Spinner count,Spinner diff,CheckBox bizarre,Spinner be,CheckBox strong,Spinner se,CheckBox sound){players.clear();HashSet<String> used=new HashSet<>();int[] colors={PINK,BLUE,GREEN,GOLD,Color.rgb(109,76,165)};for(int i=0;i<rows.size();i++){String n=rows.get(i)[0].getText().toString().trim(),t=rows.get(i)[1].getText().toString().trim();if(n.isEmpty()||!used.add(n.toLowerCase(Locale.ROOT))){toast("Doplň různá jména všech hráčů");return false;}players.add(new Player(n,t.isEmpty()?"Všeobecný přehled":t,colors[i]));}ArrayList<String> cats=new ArrayList<>();for(CheckBox x:boxes)if(x.isChecked())cats.add(x.getText().toString());if(cats.isEmpty()){toast("Vyber alespoň jeden okruh");return false;}cfg=new Config();cfg.title=trip.getText().toString().trim();if(cfg.title.isEmpty())cfg.title="Výlet";cfg.date=date.getText().toString().trim();cfg.note=note.getText().toString().trim();cfg.count=new int[]{10,20,30,40}[count.getSelectedItemPosition()];cfg.diff=diff.getSelectedItem().toString();cfg.cats=cats;cfg.bizarre=bizarre.isChecked();cfg.bizarreEvery=be.getSelectedItemPosition()==0?5:be.getSelectedItemPosition()==1?8:0;cfg.strong=strong.isChecked();cfg.strongEvery=se.getSelectedItemPosition()==0?3:se.getSelectedItemPosition()==1?4:0;cfg.sound=sound.isChecked();prefs.edit().putBoolean("sound",cfg.sound).apply();saveProfiles();return true;}

 void generate(Button b){String token=prefs.getString("token","");if(token.isEmpty()){toast("V Nastavení AI chybí osobní přístupový token");return;}b.setEnabled(false);b.setText("Generuji celý kvíz…");new Thread(()->{try{JSONObject body=new JSONObject().put("topic",brief()).put("difficulty",cfg.diff).put("count",cfg.count);HttpURLConnection c=(HttpURLConnection)new URL(prefs.getString("url",ENDPOINT)).openConnection();c.setConnectTimeout(20000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("X-App-Token",token);c.setDoOutput(true);c.getOutputStream().write(body.toString().getBytes(StandardCharsets.UTF_8));InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();String text=read(in);if(c.getResponseCode()>=400)throw new IOException(text);parse(new JSONObject(text));runOnUiThread(this::start);}catch(Exception e){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("AI kvíz není dostupný").setMessage(e.getMessage()+"\n\nMůžete zatím hrát z připravených otázek.").setPositiveButton("Hrát offline",(d,w)->{loadAsset();trim(cfg.count);start();}).setNegativeButton("Zpět",(d,w)->setup()).show());}}).start();}
 String brief(){StringBuilder s=new StringBuilder("Český a světový přehled. Okruhy: ").append(String.join(", ",cfg.cats)).append(". Přibližně 60 % otázek vztáhni k Česku. ");if(cfg.bizarre)s.append("Zařaď několik pravdivých bizarních zajímavostí. ");if(cfg.strong){s.append("Zařaď také silné okruhy hráčů: ");for(Player p:players)s.append(p.name).append(" – ").append(p.topic).append("; ");}return s.toString();}

 void start(){if(quiz.isEmpty()){toast("Kvíz neobsahuje otázky");return;}game=new State(players.size());undo.clear();redo.clear();specials();question();}
 void specials(){int[] personal=new int[players.size()];for(int i=0;i<quiz.size();i++){Question q=quiz.get(i);int owner=i%players.size();personal[owner]++;q.special="";if(cfg.strong&&cfg.strongEvery>0&&personal[owner]%cfg.strongEvery==0)q.special="🏆 Silný okruh: "+players.get(owner).topic;else if(cfg.bizarre&&cfg.bizarreEvery>0&&(i+1)%cfg.bizarreEvery==0)q.special="🤪 Bizarní svět";}if(cfg.bizarre&&cfg.bizarreEvery==0&&quiz.size()>2)quiz.get(quiz.size()/2).special="🤪 Bizarní svět";if(cfg.strong&&cfg.strongEvery==0)for(int i=0;i<players.size()&&i<quiz.size();i++)quiz.get(Math.min(quiz.size()-1,i+players.size())).special="🏆 Silný okruh: "+players.get(i).topic;}
 void question(){base();Question q=quiz.get(game.index);Player responder=players.get(game.responder);TextView who=tv((game.attempt==0?"Na tahu: ":"Přebírá: ")+responder.name,22,true);who.setTextColor(responder.color);root.addView(who);root.addView(tv("Otázka "+(game.index+1)+" z "+quiz.size()+"  •  hodnota "+num(value())+" bodu",14,false));if(!q.special.isEmpty()){TextView x=tv(q.special,16,true);x.setTextColor(q.special.contains("Bizarní")?GOLD:GREEN);root.addView(x);}root.addView(tv(q.text,23,true));answers=new LinearLayout(this);answers.setOrientation(LinearLayout.VERTICAL);root.addView(answers);for(int i=0;i<4;i++){final int choice=i;Button a=btn("ABCD".charAt(i)+")  "+q.options[i]);a.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);if(game.blocked[i]){a.setEnabled(false);a.setTextColor(Color.GRAY);}if(game.answered&&i==q.correct){a.setText("⭕  "+"ABCD".charAt(i)+")  "+q.options[i]);a.setTextColor(RED);a.setTypeface(null,Typeface.BOLD);}else if(!game.answered)a.setOnClickListener(v->answer(choice));answers.addView(a);}if(game.answered){TextView e=tv("PROČ: "+q.explanation,17,false);e.setBackgroundColor(Color.rgb(255,247,230));root.addView(e);Button n=btn(game.index+1>=quiz.size()?"Zobrazit výsledky":"Další otázka");n.setOnClickListener(v->next());root.addView(n);}else{Button pass=btn("Neví – nabídnout dalšímu hráči");pass.setOnClickListener(v->pass());root.addView(pass);Button reveal=btn("Ukončit otázku a ukázat odpověď");reveal.setOnClickListener(v->{remember();game.answered=true;sound(false);question();});root.addView(reveal);}root.addView(score());LinearLayout nav=new LinearLayout(this);Button u=btn("↶ Zpět");u.setEnabled(!undo.isEmpty());u.setOnClickListener(v->undo());Button r=btn("Vpřed ↷");r.setEnabled(!redo.isEmpty());r.setOnClickListener(v->redo());nav.addView(u,new LinearLayout.LayoutParams(0,-2,1));nav.addView(r,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);Button end=btn("Uložit rozehranou hru a skončit");end.setOnClickListener(v->quit());root.addView(end);}
 TextView score(){StringBuilder s=new StringBuilder();for(int i=0;i<players.size();i++){if(i>0)s.append("  •  ");s.append(players.get(i).name).append(" ").append(num(game.scores[i]));}TextView v=tv(s.toString(),16,true);v.setTextColor(NAVY);return v;}
 double value(){return game.attempt==0?1:game.attempt==1?.6:.3;}
 void answer(int choice){remember();Question q=quiz.get(game.index);if(choice==q.correct){game.scores[game.responder]+=value();game.correct[game.responder]++;if(game.attempt>0)game.steals[game.responder]++;game.answered=true;sound(true);}else{game.blocked[choice]=true;game.wrong[game.responder]++;if(game.attempt>=2||blocked()>=3){game.answered=true;sound(false);}else{game.attempt++;game.responder=(game.responder+1)%players.size();sound(false);}}question();}
 void pass(){remember();if(game.attempt>=2)game.answered=true;else{game.attempt++;game.responder=(game.responder+1)%players.size();}question();}
 int blocked(){int n=0;for(boolean b:game.blocked)if(b)n++;return n;}
 void next(){remember();if(game.index+1>=quiz.size()){finishQuiz();return;}game.index++;game.owner=game.index%players.size();game.responder=game.owner;game.attempt=0;game.blocked=new boolean[4];game.answered=false;question();}
 void remember(){undo.push(game.copy());if(undo.size()>100)undo.removeLast();redo.clear();}
 void undo(){if(undo.isEmpty())return;redo.push(game.copy());game=undo.pop();question();}
 void redo(){if(redo.isEmpty())return;undo.push(game.copy());game=redo.pop();question();}
 void sound(boolean ok){if(!cfg.sound)return;tones.startTone(ok?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_NACK,ok?180:120);if(Build.VERSION.SDK_INT>=26)((android.os.Vibrator)getSystemService(VIBRATOR_SERVICE)).vibrate(android.os.VibrationEffect.createOneShot(ok?45:25,80));}

 void finishQuiz(){saveGame(false);base();title("VÝSLEDKY",cfg.title+" • "+cfg.date);Integer[] order=new Integer[players.size()];for(int i=0;i<order.length;i++)order[i]=i;Arrays.sort(order,(a,b)->Double.compare(game.scores[b],game.scores[a]));for(int rank=0;rank<order.length;rank++){int i=order[rank];TextView row=tv((rank==0?"🏆 ":(rank+1)+". ")+players.get(i).name+"  •  "+num(game.scores[i])+" bodu",rank==0?25:20,true);row.setTextColor(players.get(i).color);root.addView(row);}root.addView(tv("Vítězí "+players.get(order[0]).name+"! Hra je uložená v kronice výletů.",18,false));sound(true);Button h=btn("Otevřít kroniku");h.setOnClickListener(v->history());root.addView(h);Button a=btn("Odveta se stejným nastavením");a.setOnClickListener(v->start());root.addView(a);Button m=btn("Hlavní nabídka");m.setOnClickListener(v->home());root.addView(m);}
 void quit(){new AlertDialog.Builder(this).setTitle("Ukončit hru?").setMessage("Rozehraný výlet se uloží do kroniky jako nedokončený.").setPositiveButton("Uložit a skončit",(d,w)->{saveGame(true);home();}).setNegativeButton("Pokračovat",null).show();}
 void saveGame(boolean unfinished){try{JSONArray old=new JSONArray(prefs.getString("history","[]"));JSONObject g=new JSONObject().put("id",System.currentTimeMillis()).put("title",cfg.title).put("date",cfg.date).put("note",cfg.note).put("unfinished",unfinished).put("played",game.index+1).put("total",quiz.size());JSONArray ps=new JSONArray();double best=-1;String winner="";for(int i=0;i<players.size();i++){JSONObject p=new JSONObject().put("name",players.get(i).name).put("topic",players.get(i).topic).put("score",game.scores[i]).put("correct",game.correct[i]).put("wrong",game.wrong[i]).put("steals",game.steals[i]);ps.put(p);if(game.scores[i]>best){best=game.scores[i];winner=players.get(i).name;}}g.put("players",ps).put("winner",winner);JSONArray qs=new JSONArray();for(Question q:quiz)qs.put(q.json());g.put("questions",qs);JSONArray all=new JSONArray();all.put(g);for(int i=0;i<Math.min(99,old.length());i++)all.put(old.get(i));prefs.edit().putString("history",all.toString()).apply();}catch(Exception ignored){}}

 void history(){base();title("KRONIKA VÝLETŮ","Místo, datum, hráči, vítěz i otázky zůstávají pohromadě.");try{JSONArray a=new JSONArray(prefs.getString("history","[]"));if(a.length()==0)root.addView(tv("Zatím tu není žádný odehraný výlet.",18,false));for(int i=0;i<a.length();i++){JSONObject g=a.getJSONObject(i);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(14,14,14,14);card.setBackgroundColor(SOFT);card.addView(tv(g.optString("title","Výlet"),22,true));card.addView(tv(g.optString("date")+"  •  "+(g.optBoolean("unfinished")?"Nedokončeno":"🏆 "+g.optString("winner")),16,false));JSONArray ps=g.optJSONArray("players");StringBuilder ss=new StringBuilder();for(int j=0;ps!=null&&j<ps.length();j++){if(j>0)ss.append("  •  ");JSONObject p=ps.getJSONObject(j);ss.append(p.optString("name")).append(" ").append(num(p.optDouble("score")));}card.addView(tv(ss.toString(),15,true));String note=g.optString("note");if(!note.isEmpty())card.addView(tv("„"+note+"“",15,false));final int x=i;card.setOnClickListener(v->historyDetail(x));root.addView(card);Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,12));}}catch(Exception e){root.addView(tv("Historii se nepodařilo načíst.",16,false));}Button b=btn("Zpět");b.setOnClickListener(v->home());root.addView(b);}
 void historyDetail(int ix){base();try{JSONObject g=new JSONArray(prefs.getString("history","[]")).getJSONObject(ix);title(g.optString("title"),g.optString("date")+" • "+(g.optBoolean("unfinished")?"nedokončeno":"vítěz: "+g.optString("winner")));String note=g.optString("note");if(!note.isEmpty())root.addView(tv(note,17,false));section("Výsledky");JSONArray ps=g.getJSONArray("players");for(int i=0;i<ps.length();i++){JSONObject p=ps.getJSONObject(i);root.addView(tv(p.getString("name")+": "+num(p.getDouble("score"))+" bodu  •  správně "+p.optInt("correct")+"  •  převzaté "+p.optInt("steals"),17,true));}section("Otázky z výletu");JSONArray qs=g.optJSONArray("questions");for(int i=0;qs!=null&&i<qs.length();i++){JSONObject q=qs.getJSONObject(i);root.addView(tv((i+1)+". "+q.optString("question"),16,true));root.addView(tv("Správně: "+q.getJSONArray("options").optString(q.optInt("correct"))+"\n"+q.optString("explanation"),14,false));}}catch(Exception e){root.addView(tv("Záznam se nepodařilo otevřít.",16,false));}Button b=btn("Zpět do kroniky");b.setOnClickListener(v->history());root.addView(b);}
 void stats(){base();title("TABULKA HRÁČŮ","Dlouhodobé výsledky z dokončených výletů.");HashMap<String,Stat> map=new HashMap<>();try{JSONArray a=new JSONArray(prefs.getString("history","[]"));for(int i=0;i<a.length();i++){JSONObject g=a.getJSONObject(i);if(g.optBoolean("unfinished"))continue;JSONArray ps=g.getJSONArray("players");for(int j=0;j<ps.length();j++){JSONObject p=ps.getJSONObject(j);String n=p.getString("name");Stat s=map.get(n);if(s==null){s=new Stat(n);map.put(n,s);}s.games++;s.points+=p.optDouble("score");s.correct+=p.optInt("correct");s.wrong+=p.optInt("wrong");s.steals+=p.optInt("steals");if(n.equals(g.optString("winner")))s.wins++;}}}catch(Exception ignored){}ArrayList<Stat> list=new ArrayList<>(map.values());Collections.sort(list,(a,b)->Integer.compare(b.wins,a.wins));if(list.isEmpty())root.addView(tv("Statistiky se objeví po první dokončené hře.",18,false));int rank=1;for(Stat s:list){double hit=s.correct+s.wrong==0?0:100.0*s.correct/(s.correct+s.wrong);root.addView(tv((rank++)+". "+s.name+"  •  "+s.wins+" výher",21,true));root.addView(tv(s.games+" her  •  "+num(s.points)+" bodů  •  úspěšnost "+Math.round(hit)+" %  •  převzaté "+s.steals,15,false));}Button b=btn("Zpět");b.setOnClickListener(v->home());root.addView(b);}

 void connection(){base();title("PŘIPOJENÍ K AI","OpenAI klíč zůstává pouze na bezpečném serveru.");EditText u=edit("Adresa serveru",prefs.getString("url",ENDPOINT));root.addView(u);EditText t=edit("Osobní přístupový token",prefs.getString("token",""));t.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);root.addView(t);Button s=btn("Uložit");s.setOnClickListener(v->{prefs.edit().putString("url",u.getText().toString().trim()).putString("token",t.getText().toString().trim()).apply();toast("Nastavení uloženo");home();});root.addView(s);Button b=btn("Zpět");b.setOnClickListener(v->home());root.addView(b);}
 void saveProfiles(){try{JSONArray a=new JSONArray();for(Player p:players)a.put(new JSONObject().put("name",p.name).put("topic",p.topic));prefs.edit().putString("profiles",a.toString()).apply();}catch(Exception ignored){}}
 String[][] profiles(){try{JSONArray a=new JSONArray(prefs.getString("profiles","[]"));String[][] r=new String[a.length()][2];for(int i=0;i<a.length();i++){r[i][0]=a.getJSONObject(i).optString("name");r[i][1]=a.getJSONObject(i).optString("topic");}return r;}catch(Exception e){return new String[0][0];}}
 void trim(int n){while(quiz.size()>n)quiz.remove(quiz.size()-1);}
 void loadAsset(){try{parse(new JSONObject(read(getAssets().open("default_quiz.json"))));}catch(Exception e){toast("Otázky se nepodařilo načíst");}}
 void parse(JSONObject o)throws Exception{quiz.clear();JSONArray a=o.getJSONArray("questions");for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);JSONArray ar=x.getJSONArray("options");String[] opts=new String[4];for(int j=0;j<4;j++)opts[j]=ar.getString(j);quiz.add(new Question(x.getString("question"),opts,x.getInt("correct"),x.getString("explanation"),x.optBoolean("hard")));}}
 String read(InputStream i)throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] x=new byte[4096];int n;while((n=i.read(x))>0)b.write(x,0,n);return b.toString("UTF-8");}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 public void onBackPressed(){home();}

 static class Player{String name,topic;int color;Player(String n,String t,int c){name=n;topic=t;color=c;}}
 static class Question{String text,explanation,special="";String[] options;int correct;boolean hard;Question(String t,String[]o,int c,String e,boolean h){text=t;options=o;correct=c;explanation=e;hard=h;}JSONObject json()throws Exception{return new JSONObject().put("question",text).put("options",new JSONArray(options)).put("correct",correct).put("explanation",explanation).put("hard",hard).put("special",special);}}
 static class Config{String title="Výlet",date="",note="",diff="Vyvážená";int count=40,bizarreEvery=5,strongEvery=3;boolean bizarre=true,strong=true,sound=true;ArrayList<String> cats=new ArrayList<>();}
 static class State{int index,owner,responder,attempt;double[] scores;int[] correct,wrong,steals;boolean[] blocked=new boolean[4];boolean answered;State(int n){scores=new double[n];correct=new int[n];wrong=new int[n];steals=new int[n];}State copy(){State x=new State(scores.length);x.index=index;x.owner=owner;x.responder=responder;x.attempt=attempt;x.scores=scores.clone();x.correct=correct.clone();x.wrong=wrong.clone();x.steals=steals.clone();x.blocked=blocked.clone();x.answered=answered;return x;}}
 static class Stat{String name;int games,wins,correct,wrong,steals;double points;Stat(String n){name=n;}}
}
