package cz.ctuprotebe.vyletnikviz;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.net.Uri;
import android.text.InputType;
import android.util.Base64;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;

public class MainActivity extends Activity {
 static final String ENDPOINT="https://vyletni-kviz-api.daniel-pohl.chatgpt.site/generate";
 static final String OPENAI_ENDPOINT="https://api.openai.com/v1/responses",KEY_ALIAS="vyletni_kviz_openai_key";
 static final String[] CATS={"Česko","Svět","Historie","Zeměpis","Příroda","Věda a technika","Kultura","Film a televize","Hudba","Sport","Český jazyk","Gastronomie","Zajímavosti"};
 final int NAVY=Color.rgb(25,50,74),RED=Color.rgb(217,45,58),PINK=Color.rgb(179,60,134),BLUE=Color.rgb(38,119,168),GREEN=Color.rgb(32,132,92),GOLD=Color.rgb(190,132,22),SOFT=Color.rgb(242,246,243),CREAM=Color.rgb(251,248,239),INK=Color.rgb(29,42,47),ORANGE=Color.rgb(232,124,64);
 LinearLayout root,answers; SharedPreferences prefs; ToneGenerator tones;
 ArrayList<Question> quiz=new ArrayList<>(); ArrayList<Player> players=new ArrayList<>(); Config cfg; State game;
 ArrayList<String> selectedPhotos=new ArrayList<>(); LinearLayout photoHolder; Button photoButton;
 int pendingPhotoHistoryIndex=-1;
 ArrayDeque<State> undo=new ArrayDeque<>(),redo=new ArrayDeque<>();
 static final int PICK_PHOTOS=4401;

 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("quiz",MODE_PRIVATE);tones=new ToneGenerator(AudioManager.STREAM_MUSIC,70);home();}
 protected void onDestroy(){tones.release();super.onDestroy();}
 TextView tv(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(23,33,43));v.setPadding(12,10,12,10);if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
 GradientDrawable shape(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);return g;}
 void gap(View v,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,top,0,0);v.setLayoutParams(p);}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setTypeface(null,Typeface.BOLD);b.setAllCaps(false);b.setMinHeight(58);b.setPadding(18,10,18,10);b.setBackground(shape(NAVY,22));gap(b,12);return b;}
 Button secondary(String s){Button b=btn(s);b.setTextColor(NAVY);b.setBackground(shape(Color.WHITE,22));return b;}
 EditText edit(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextSize(17);e.setTextColor(INK);e.setHintTextColor(Color.rgb(112,122,120));e.setPadding(18,10,18,10);e.setMinHeight(58);e.setBackground(shape(Color.WHITE,18));gap(e,8);return e;}
 Spinner spin(String... a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
 void base(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(CREAM);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,34,28,52);s.addView(root);setContentView(s);}
 void title(String a,String b){TextView h=tv(a,30,true);h.setTextColor(NAVY);h.setLetterSpacing(.03f);root.addView(h);if(b!=null){TextView sub=tv(b,16,false);sub.setTextColor(Color.rgb(80,92,88));root.addView(sub);}}
 void section(String s){TextView h=tv(s,20,true);h.setTextColor(NAVY);h.setPadding(8,24,8,8);root.addView(h);}
 String today(){return new SimpleDateFormat("dd. MM. yyyy",Locale.forLanguageTag("cs-CZ")).format(new Date());}
 String num(double x){return Math.abs(x-Math.rint(x))<.001?String.valueOf((int)Math.rint(x)):String.format(Locale.forLanguageTag("cs-CZ"),"%.1f",x);}

 void home(){base();TextView mark=tv("⛰  VÝLETNÍ KVÍZ",30,true);mark.setTextColor(NAVY);root.addView(mark);root.addView(tv("Každý výlet má svůj příběh. Tenhle bude mít i vítěze.",18,false));Button n=btn("＋  Začít nový výlet");n.setBackground(shape(ORANGE,24));n.setOnClickListener(v->setup());root.addView(n);if(prefs.contains("resume")){Button c=btn("▶  Pokračovat v rozehrané hře");c.setBackground(shape(GREEN,24));c.setOnClickListener(v->resume());root.addView(c);}Button h=secondary("📖  Kronika výletů");h.setOnClickListener(v->history());root.addView(h);Button s=secondary("🏆  Dlouhodobá tabulka");s.setOnClickListener(v->stats());root.addView(s);Button q=secondary("⚡  Rychlá hra ve dvou");q.setOnClickListener(v->quick());root.addView(q);Button c=secondary("⚙  Připojení k AI");c.setOnClickListener(v->connection());root.addView(c);TextView info=tv("Aplikace hlídá pořadí, přebírání i body. Připravený kvíz funguje také bez internetu.",14,false);info.setPadding(16,24,16,8);root.addView(info);}
 void quick(){cfg=new Config();cfg.title="Rychlý kvíz";cfg.date=today();players.clear();players.add(new Player("Barča","Psychologie",PINK));players.add(new Player("Dominik","Lední hokej",BLUE));loadAsset();start();}

 void setup(){pendingPhotoHistoryIndex=-1;selectedPhotos.clear();base();title("NOVÝ VÝLET","Nejdřív vzpomínka, potom hráči a pravidla.");section("Výlet");EditText trip=edit("Název, například Okoř","Výlet");root.addView(trip);EditText date=edit("Datum",today());root.addView(date);EditText note=edit("Poznámka nebo hláška z výletu","");root.addView(note);section("Fotky na památku");photoHolder=new LinearLayout(this);photoHolder.setOrientation(LinearLayout.HORIZONTAL);root.addView(photoHolder);photoButton=secondary("＋ Přidat fotky (max. 5)");photoButton.setOnClickListener(v->pickPhotos());root.addView(photoButton);
  section("Hráči v pořadí");LinearLayout holder=new LinearLayout(this);holder.setOrientation(LinearLayout.VERTICAL);root.addView(holder);ArrayList<EditText[]> rows=new ArrayList<>();String[][] saved=profiles();if(saved.length<2)saved=new String[][]{{"Barča","Psychologie"},{"Dominik","Lední hokej"}};for(int i=0;i<Math.min(5,saved.length);i++)playerRow(holder,rows,saved[i][0],saved[i][1]);Button add=btn("+ Přidat hráče");add.setOnClickListener(v->{if(rows.size()<5)playerRow(holder,rows,"","");else toast("Maximum je 5 hráčů");});root.addView(add);
  section("Délka a obtížnost");Spinner count=spin("10 otázek","20 otázek","30 otázek","40 otázek");root.addView(count);Spinner diff=spin("Vyvážená","Pohodová","Náročná");root.addView(diff);
  section("Okruhy");ArrayList<CheckBox> boxes=new ArrayList<>();for(String c:CATS){CheckBox x=new CheckBox(this);x.setText(c);x.setTextSize(16);x.setChecked(Arrays.asList("Česko","Svět","Historie","Příroda","Věda a technika","Kultura","Zajímavosti").contains(c));boxes.add(x);root.addView(x);}
  section("Herní módy");CheckBox bizarre=check("Bizarní svět – pravdivé a podivné otázky",true);root.addView(bizarre);Spinner be=spin("Každých 5 otázek","Každých 8 otázek","Jednou za hru");root.addView(be);CheckBox strong=check("Silné okruhy jednotlivých hráčů",true);root.addView(strong);Spinner se=spin("Každá 3. osobní otázka","Každá 4. osobní otázka","Jednou za hru");root.addView(se);CheckBox sound=check("Zvuky a jemné vibrace",prefs.getBoolean("sound",true));root.addView(sound);
  Button off=btn("Připravit offline kvíz");off.setOnClickListener(v->{if(collect(rows,boxes,trip,date,note,count,diff,bizarre,be,strong,se,sound)){offlineStart();}});root.addView(off);Button ai=btn("Vygenerovat nový kvíz s AI");ai.setOnClickListener(v->{if(collect(rows,boxes,trip,date,note,count,diff,bizarre,be,strong,se,sound))generate(ai);});root.addView(ai);Button back=btn("Zpět");back.setOnClickListener(v->home());root.addView(back);
 }
 void offlineStart(){cfg.personalized=false;if(cfg.bizarre||cfg.strong){new AlertDialog.Builder(this).setTitle("Offline kvíz").setMessage("Vlastní silné okruhy a přesně řízené bizarní otázky vytváří AI. Offline sada je všeobecný český a světový přehled bez falešných tematických štítků.").setPositiveButton("Hrát všeobecný kvíz",(d,w)->{loadAsset();trim(cfg.count);start();}).setNegativeButton("Zpět",null).show();}else{loadAsset();trim(cfg.count);start();}}
 CheckBox check(String s,boolean on){CheckBox c=new CheckBox(this);c.setText(s);c.setTextSize(16);c.setChecked(on);return c;}
 void playerRow(LinearLayout holder,ArrayList<EditText[]> rows,String name,String topic){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(10,8,10,8);card.setBackgroundColor(SOFT);EditText n=edit("Jméno hráče",name),t=edit("Silný okruh, například lední hokej",topic);card.addView(n);card.addView(t);Button del=btn("Odebrat hráče");del.setOnClickListener(v->{if(rows.size()<=2){toast("Musí zůstat alespoň 2 hráči");return;}int i=holder.indexOfChild(card);holder.removeView(card);rows.remove(i);});card.addView(del);holder.addView(card);rows.add(new EditText[]{n,t});}
 boolean collect(ArrayList<EditText[]> rows,ArrayList<CheckBox> boxes,EditText trip,EditText date,EditText note,Spinner count,Spinner diff,CheckBox bizarre,Spinner be,CheckBox strong,Spinner se,CheckBox sound){players.clear();HashSet<String> used=new HashSet<>();int[] colors={PINK,BLUE,GREEN,GOLD,Color.rgb(109,76,165)};for(int i=0;i<rows.size();i++){String n=rows.get(i)[0].getText().toString().trim(),t=rows.get(i)[1].getText().toString().trim();if(n.isEmpty()||!used.add(n.toLowerCase(Locale.ROOT))){toast("Doplň různá jména všech hráčů");return false;}players.add(new Player(n,t.isEmpty()?"Všeobecný přehled":t,colors[i]));}ArrayList<String> cats=new ArrayList<>();for(CheckBox x:boxes)if(x.isChecked())cats.add(x.getText().toString());if(cats.isEmpty()){toast("Vyber alespoň jeden okruh");return false;}cfg=new Config();cfg.title=trip.getText().toString().trim();if(cfg.title.isEmpty())cfg.title="Výlet";cfg.date=date.getText().toString().trim();cfg.note=note.getText().toString().trim();cfg.photos.addAll(selectedPhotos);cfg.count=new int[]{10,20,30,40}[count.getSelectedItemPosition()];cfg.diff=diff.getSelectedItem().toString();cfg.cats=cats;cfg.bizarre=bizarre.isChecked();cfg.bizarreEvery=be.getSelectedItemPosition()==0?5:be.getSelectedItemPosition()==1?8:0;cfg.strong=strong.isChecked();cfg.strongEvery=se.getSelectedItemPosition()==0?3:se.getSelectedItemPosition()==1?4:0;cfg.sound=sound.isChecked();prefs.edit().putBoolean("sound",cfg.sound).apply();saveProfiles();return true;}

 void pickPhotos(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK_PHOTOS);}
 protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=PICK_PHOTOS||resultCode!=RESULT_OK||data==null)return;ArrayList<Uri> incoming=new ArrayList<>();if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)incoming.add(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)incoming.add(data.getData());boolean overflow=false;for(Uri uri:incoming){if(selectedPhotos.size()>=5){overflow=true;break;}String s=uri.toString();if(selectedPhotos.contains(s))continue;try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}selectedPhotos.add(s);}if(pendingPhotoHistoryIndex>=0){int ix=pendingPhotoHistoryIndex;pendingPhotoHistoryIndex=-1;updateHistoryPhotos(ix);historyDetail(ix);}else renderSelectedPhotos();if(overflow)toast("K výletu lze uložit nejvýše 5 fotek");}
 void renderSelectedPhotos(){if(photoHolder==null)return;photoHolder.removeAllViews();for(String value:selectedPhotos){final String uri=value;ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);try{image.setImageURI(Uri.parse(uri));}catch(Exception ignored){}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,180,1);p.setMargins(4,4,4,4);image.setLayoutParams(p);image.setContentDescription("Fotka z výletu, klepnutím odebrat");image.setOnClickListener(v->{selectedPhotos.remove(uri);renderSelectedPhotos();});photoHolder.addView(image);}if(photoButton!=null)photoButton.setText(selectedPhotos.isEmpty()?"＋ Přidat fotky (max. 5)":"Fotky "+selectedPhotos.size()+"/5  •  klepnutím odeberete");}

 void generate(Button b){String apiKey=getSecret();if(apiKey.isEmpty()){toast("Nejdřív vložte OpenAI API klíč v Připojení k AI");connection();return;}b.setEnabled(false);b.setText("Generuji celý kvíz…");new Thread(()->{try{JSONObject body=openAiBody();HttpURLConnection c=(HttpURLConnection)new URL(OPENAI_ENDPOINT).openConnection();c.setConnectTimeout(20000);c.setReadTimeout(180000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+apiKey);c.setDoOutput(true);c.getOutputStream().write(body.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();String text=read(in);if(code>=400)throw new IOException(openAiError(text,code));JSONObject response=new JSONObject(text);String output="";JSONArray out=response.optJSONArray("output");for(int i=0;out!=null&&i<out.length()&&output.isEmpty();i++){JSONArray content=out.getJSONObject(i).optJSONArray("content");for(int j=0;content!=null&&j<content.length();j++){JSONObject item=content.getJSONObject(j);if("output_text".equals(item.optString("type"))){output=item.optString("text");break;}}}if(output.isEmpty())throw new IOException("OpenAI nevrátilo žádné otázky.");parse(new JSONObject(output));if(quiz.size()!=cfg.count)throw new IOException("AI vrátila "+quiz.size()+" místo "+cfg.count+" otázek.");cfg.personalized=true;runOnUiThread(this::start);}catch(Exception e){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("AI kvíz není dostupný").setMessage(e.getMessage()+"\n\nMůžete zatím hrát z připravených otázek.").setPositiveButton("Hrát offline",(d,w)->{loadAsset();trim(cfg.count);start();}).setNegativeButton("Zpět",(d,w)->setup()).show());}}).start();}
 JSONObject openAiBody()throws Exception{JSONObject question=new JSONObject().put("type","object").put("additionalProperties",false).put("required",new JSONArray(Arrays.asList("question","options","correct","explanation","hard"))).put("properties",new JSONObject().put("question",new JSONObject().put("type","string")).put("options",new JSONObject().put("type","array").put("minItems",4).put("maxItems",4).put("items",new JSONObject().put("type","string"))).put("correct",new JSONObject().put("type","integer").put("minimum",0).put("maximum",3)).put("explanation",new JSONObject().put("type","string")).put("hard",new JSONObject().put("type","boolean")));
  JSONObject schema=new JSONObject().put("type","object").put("additionalProperties",false).put("required",new JSONArray().put("questions")).put("properties",new JSONObject().put("questions",new JSONObject().put("type","array").put("minItems",cfg.count).put("maxItems",cfg.count).put("items",question)));
  String prompt="Vytvoř přesně "+cfg.count+" samostatných kvízových otázek v češtině. "+brief()+" Obtížnost: "+cfg.diff+". Každá otázka musí mít přesně čtyři různé věrohodné možnosti, právě jednu jednoznačně správnou odpověď a stručné zajímavé vysvětlení. Střídej obory, neopakuj otázky, nepoužívej pravda/nepravda ani slovní chytáky. Pole correct je index 0 až 3 a hard označuje těžší otázku.";
  JSONArray input=new JSONArray().put(new JSONObject().put("role","system").put("content","Jsi pečlivý český autor faktografických kvízů. Před odevzdáním interně ověř správnost, jednoznačnost a počet otázek.")).put(new JSONObject().put("role","user").put("content",prompt));
  return new JSONObject().put("model","gpt-4o-mini").put("input",input).put("text",new JSONObject().put("format",new JSONObject().put("type","json_schema").put("name","vyletni_kviz").put("strict",true).put("schema",schema)));
 }
 String openAiError(String raw,int code){try{String m=new JSONObject(raw).optJSONObject("error").optString("message");if(!m.isEmpty())return "OpenAI: "+m;}catch(Exception ignored){}return "OpenAI odpovědělo chybou "+code+".";}
 String brief(){StringBuilder s=new StringBuilder("Český a světový přehled. Okruhy: ").append(String.join(", ",cfg.cats)).append(". Přibližně 60 % otázek vztáhni k Česku. ");if(cfg.bizarre)s.append("Bizarní otázka musí být pravdivá, překvapivá a zároveň naučná. ");if(cfg.strong){s.append("Silné okruhy hráčů: ");for(Player p:players)s.append(p.name).append(" – ").append(p.topic).append("; ");}if(cfg.personalized||cfg.bizarre||cfg.strong){s.append(" Dodrž přesně tato zvláštní zadání podle pořadí otázek: ");for(int i=0;i<cfg.count;i++){String x=specialForIndex(i);if(!x.isEmpty())s.append(i+1).append(" = ").append(x).append("; ");}}return s.toString();}

 void start(){if(quiz.isEmpty()){toast("Kvíz neobsahuje otázky");return;}game=new State(players.size());undo.clear();redo.clear();specials();question();}
 void specials(){for(int i=0;i<quiz.size();i++)quiz.get(i).special=cfg.personalized?specialForIndex(i):"";}
 String specialForIndex(int i){if(players.isEmpty())return "";int owner=i%players.size(),personal=i/players.size()+1;if(cfg.strong&&((cfg.strongEvery>0&&personal%cfg.strongEvery==0)||(cfg.strongEvery==0&&i==players.size()+owner)))return "🏆 Silný okruh pro "+players.get(owner).name+": "+players.get(owner).topic;if(cfg.bizarre&&((cfg.bizarreEvery>0&&(i+1)%cfg.bizarreEvery==0)||(cfg.bizarreEvery==0&&i==cfg.count/2)))return "🤪 Bizarní svět";return "";}
 void question(){saveResume();base();Question q=quiz.get(game.index);Player owner=players.get(game.owner),responder=players.get(game.responder);TextView who=tv((game.attempt==0?"Na tahu: ":"Přebírá: ")+responder.name,22,true);who.setTextColor(responder.color);root.addView(who);if(game.attempt>0)root.addView(tv("Původní otázka pro "+owner.name+"  •  pokus "+(game.attempt+1)+" z "+players.size(),14,false));root.addView(tv("Otázka "+(game.index+1)+" z "+quiz.size()+"  •  za "+num(value())+" bodu",14,false));if(!q.special.isEmpty()){TextView x=tv(q.special,16,true);x.setTextColor(q.special.contains("Bizarní")?GOLD:GREEN);root.addView(x);}root.addView(tv(q.text,23,true));answers=new LinearLayout(this);answers.setOrientation(LinearLayout.VERTICAL);root.addView(answers);for(int i=0;i<4;i++){final int choice=i;Button a=btn("ABCD".charAt(i)+")  "+q.options[i]);a.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);if(game.blocked[i]){a.setEnabled(false);a.setText("✕  "+"ABCD".charAt(i)+")  "+q.options[i]);a.setTextColor(Color.GRAY);}if(game.answered&&i==q.correct){a.setText("⭕  "+"ABCD".charAt(i)+")  "+q.options[i]);a.setTextColor(RED);a.setTypeface(null,Typeface.BOLD);}else if(!game.answered&&!game.blocked[i])a.setOnClickListener(v->answer(choice));answers.addView(a);}if(game.answered){TextView e=tv("PROČ: "+q.explanation,17,false);e.setBackgroundColor(Color.rgb(255,247,230));root.addView(e);Button n=btn(game.index+1>=quiz.size()?"Zobrazit výsledky":"Další otázka");n.setOnClickListener(v->next());root.addView(n);}else{Button pass=btn(GameRules.hasNextPlayer(game.attempt,players.size())?"Neví – předat hráči "+players.get(GameRules.responder(game.owner,game.attempt+1,players.size())).name:"Neví – ukázat odpověď");pass.setOnClickListener(v->pass());root.addView(pass);Button reveal=secondary("Ukončit otázku a ukázat odpověď");reveal.setOnClickListener(v->{remember();game.answered=true;sound(false);question();});root.addView(reveal);}root.addView(score());LinearLayout nav=new LinearLayout(this);Button u=secondary("↶ Zpět");u.setEnabled(!undo.isEmpty());u.setOnClickListener(v->undo());Button r=secondary("Vpřed ↷");r.setEnabled(!redo.isEmpty());r.setOnClickListener(v->redo());nav.addView(u,new LinearLayout.LayoutParams(0,-2,1));nav.addView(r,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);Button end=secondary("Uložit rozehranou hru a skončit");end.setOnClickListener(v->quit());root.addView(end);}
 TextView score(){StringBuilder s=new StringBuilder();for(int i=0;i<players.size();i++){if(i>0)s.append("  •  ");s.append(players.get(i).name).append(" ").append(num(game.scores[i]));}TextView v=tv(s.toString(),16,true);v.setTextColor(NAVY);return v;}
 double value(){return GameRules.pointValue(game.attempt);}
 void answer(int choice){remember();Question q=quiz.get(game.index);if(choice==q.correct){game.scores[game.responder]+=value();game.correct[game.responder]++;if(game.attempt>0)game.steals[game.responder]++;game.answered=true;sound(true);}else{game.blocked[choice]=true;game.wrong[game.responder]++;if(!GameRules.hasNextPlayer(game.attempt,players.size())||blocked()>=3){game.answered=true;sound(false);}else{game.attempt++;game.responder=GameRules.responder(game.owner,game.attempt,players.size());sound(false);}}question();}
 void pass(){remember();if(!GameRules.hasNextPlayer(game.attempt,players.size()))game.answered=true;else{game.attempt++;game.responder=GameRules.responder(game.owner,game.attempt,players.size());}question();}
 int blocked(){int n=0;for(boolean b:game.blocked)if(b)n++;return n;}
 void next(){remember();if(game.index+1>=quiz.size()){finishQuiz();return;}game.index++;game.owner=game.index%players.size();game.responder=game.owner;game.attempt=0;game.blocked=new boolean[4];game.answered=false;question();}
 void remember(){undo.push(game.copy());if(undo.size()>100)undo.removeLast();redo.clear();}
 void undo(){if(undo.isEmpty())return;redo.push(game.copy());game=undo.pop();question();}
 void redo(){if(redo.isEmpty())return;undo.push(game.copy());game=redo.pop();question();}
 void sound(boolean ok){if(!cfg.sound)return;tones.startTone(ok?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_NACK,ok?180:120);if(Build.VERSION.SDK_INT>=26)((android.os.Vibrator)getSystemService(VIBRATOR_SERVICE)).vibrate(android.os.VibrationEffect.createOneShot(ok?45:25,80));}
 JSONArray doubles(double[] a)throws JSONException{JSONArray x=new JSONArray();for(double v:a)x.put(v);return x;}
 JSONArray ints(int[] a){JSONArray x=new JSONArray();for(int v:a)x.put(v);return x;}
 JSONArray bools(boolean[] a){JSONArray x=new JSONArray();for(boolean v:a)x.put(v);return x;}
 void saveResume(){if(cfg==null||game==null||quiz.isEmpty())return;try{JSONObject o=new JSONObject();o.put("config",new JSONObject().put("title",cfg.title).put("date",cfg.date).put("note",cfg.note).put("photos",new JSONArray(cfg.photos)).put("diff",cfg.diff).put("count",cfg.count).put("bizarre",cfg.bizarre).put("bizarreEvery",cfg.bizarreEvery).put("strong",cfg.strong).put("strongEvery",cfg.strongEvery).put("sound",cfg.sound).put("personalized",cfg.personalized).put("cats",new JSONArray(cfg.cats)));JSONArray ps=new JSONArray();for(Player p:players)ps.put(new JSONObject().put("name",p.name).put("topic",p.topic).put("color",p.color));o.put("players",ps);JSONArray qs=new JSONArray();for(Question q:quiz)qs.put(q.json());o.put("questions",qs);o.put("state",new JSONObject().put("index",game.index).put("owner",game.owner).put("responder",game.responder).put("attempt",game.attempt).put("answered",game.answered).put("scores",doubles(game.scores)).put("correct",ints(game.correct)).put("wrong",ints(game.wrong)).put("steals",ints(game.steals)).put("blocked",bools(game.blocked)));prefs.edit().putString("resume",o.toString()).apply();}catch(Exception ignored){}}
 void resume(){try{JSONObject o=new JSONObject(prefs.getString("resume",""));JSONObject c=o.getJSONObject("config");cfg=new Config();cfg.title=c.optString("title","Výlet");cfg.date=c.optString("date");cfg.note=c.optString("note");JSONArray ph=c.optJSONArray("photos");for(int i=0;ph!=null&&i<ph.length();i++)cfg.photos.add(ph.getString(i));cfg.diff=c.optString("diff","Vyvážená");cfg.count=c.optInt("count",40);cfg.bizarre=c.optBoolean("bizarre");cfg.bizarreEvery=c.optInt("bizarreEvery",5);cfg.strong=c.optBoolean("strong");cfg.strongEvery=c.optInt("strongEvery",3);cfg.sound=c.optBoolean("sound",true);cfg.personalized=c.optBoolean("personalized",false);cfg.cats.clear();JSONArray ca=c.optJSONArray("cats");for(int i=0;ca!=null&&i<ca.length();i++)cfg.cats.add(ca.getString(i));players.clear();JSONArray ps=o.getJSONArray("players");for(int i=0;i<ps.length();i++){JSONObject p=ps.getJSONObject(i);players.add(new Player(p.getString("name"),p.optString("topic"),p.optInt("color",BLUE)));}quiz.clear();JSONArray qs=o.getJSONArray("questions");for(int i=0;i<qs.length();i++){JSONObject x=qs.getJSONObject(i);JSONArray ar=x.getJSONArray("options");String[] opts=new String[4];for(int j=0;j<4;j++)opts[j]=ar.getString(j);Question q=new Question(x.getString("question"),opts,x.getInt("correct"),x.optString("explanation"),x.optBoolean("hard"));q.special=x.optString("special");quiz.add(q);}JSONObject st=o.getJSONObject("state");game=new State(players.size());game.index=st.optInt("index");game.owner=st.optInt("owner");game.responder=st.optInt("responder");game.attempt=st.optInt("attempt");game.answered=st.optBoolean("answered");JSONArray a=st.getJSONArray("scores");for(int i=0;i<game.scores.length;i++)game.scores[i]=a.optDouble(i);a=st.getJSONArray("correct");for(int i=0;i<game.correct.length;i++)game.correct[i]=a.optInt(i);a=st.getJSONArray("wrong");for(int i=0;i<game.wrong.length;i++)game.wrong[i]=a.optInt(i);a=st.getJSONArray("steals");for(int i=0;i<game.steals.length;i++)game.steals[i]=a.optInt(i);a=st.getJSONArray("blocked");for(int i=0;i<4;i++)game.blocked[i]=a.optBoolean(i);undo.clear();redo.clear();question();}catch(Exception e){prefs.edit().remove("resume").apply();toast("Rozehranou hru se nepodařilo obnovit");home();}}

 String winnerNames(){if(game==null||players.isEmpty())return "";double best=-Double.MAX_VALUE;for(double s:game.scores)best=Math.max(best,s);ArrayList<String> w=new ArrayList<>();for(int i=0;i<players.size();i++)if(Math.abs(game.scores[i]-best)<.001)w.add(players.get(i).name);return String.join(" a ",w);}
 void finishQuiz(){prefs.edit().remove("resume").apply();saveGame(false);base();title("VÝSLEDKY",cfg.title+" • "+cfg.date);Integer[] order=new Integer[players.size()];for(int i=0;i<order.length;i++)order[i]=i;Arrays.sort(order,(a,b)->Double.compare(game.scores[b],game.scores[a]));for(int rank=0;rank<order.length;rank++){int i=order[rank];TextView row=tv((Math.abs(game.scores[i]-game.scores[order[0]])<.001?"🏆 ":(rank+1)+". ")+players.get(i).name+"  •  "+num(game.scores[i])+" bodu",rank==0?25:20,true);row.setTextColor(players.get(i).color);root.addView(row);}String wn=winnerNames();root.addView(tv((wn.contains(" a ")?"Remíza: ":"Vítězí ")+wn+"! Hra je uložená v kronice výletů.",18,false));sound(true);Button photo=btn("📷 Přidat fotky k tomuto výletu");photo.setOnClickListener(v->editHistoryPhotos(0));root.addView(photo);Button h=btn("Otevřít kroniku");h.setOnClickListener(v->history());root.addView(h);Button a=secondary("Odveta se stejným nastavením");a.setOnClickListener(v->start());root.addView(a);Button m=secondary("Hlavní nabídka");m.setOnClickListener(v->home());root.addView(m);}
 void quit(){new AlertDialog.Builder(this).setTitle("Přerušit hru?").setMessage("Průběh bezpečně uložíme. Na hlavní obrazovce pak zvolíte Pokračovat v rozehrané hře.").setPositiveButton("Uložit a skončit",(d,w)->{saveResume();home();}).setNegativeButton("Pokračovat",null).show();}
 void saveGame(boolean unfinished){try{JSONArray old=new JSONArray(prefs.getString("history","[]"));JSONObject g=new JSONObject().put("id",System.currentTimeMillis()).put("title",cfg.title).put("date",cfg.date).put("note",cfg.note).put("photos",new JSONArray(cfg.photos)).put("unfinished",unfinished).put("played",game.index+1).put("total",quiz.size());JSONArray ps=new JSONArray();for(int i=0;i<players.size();i++){JSONObject p=new JSONObject().put("name",players.get(i).name).put("topic",players.get(i).topic).put("score",game.scores[i]).put("correct",game.correct[i]).put("wrong",game.wrong[i]).put("steals",game.steals[i]);ps.put(p);}g.put("players",ps).put("winner",winnerNames());JSONArray qs=new JSONArray();for(Question q:quiz)qs.put(q.json());g.put("questions",qs);JSONArray all=new JSONArray();all.put(g);for(int i=0;i<Math.min(99,old.length());i++)all.put(old.get(i));prefs.edit().putString("history",all.toString()).apply();}catch(Exception ignored){}}

 void history(){base();title("KRONIKA VÝLETŮ","Místo, datum, hráči, vítěz, fotky i otázky zůstávají pohromadě.");try{JSONArray a=new JSONArray(prefs.getString("history","[]"));if(a.length()==0)root.addView(tv("Zatím tu není žádný odehraný výlet.",18,false));for(int i=0;i<a.length();i++){JSONObject g=a.getJSONObject(i);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(14,14,14,14);card.setBackgroundColor(SOFT);card.addView(tv(g.optString("title","Výlet"),22,true));card.addView(tv(g.optString("date")+"  •  "+(g.optBoolean("unfinished")?"Nedokončeno":"🏆 "+g.optString("winner")),16,false));JSONArray ph=g.optJSONArray("photos");if(ph!=null&&ph.length()>0){addPhotoGallery(card,ph,110);card.addView(tv("📷 "+ph.length()+" "+(ph.length()==1?"fotka":"fotek"),14,false));}JSONArray ps=g.optJSONArray("players");StringBuilder ss=new StringBuilder();for(int j=0;ps!=null&&j<ps.length();j++){if(j>0)ss.append("  •  ");JSONObject p=ps.getJSONObject(j);ss.append(p.optString("name")).append(" ").append(num(p.optDouble("score")));}card.addView(tv(ss.toString(),15,true));String note=g.optString("note");if(!note.isEmpty())card.addView(tv("„"+note+"“",15,false));final int x=i;card.setOnClickListener(v->historyDetail(x));root.addView(card);Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,12));}}catch(Exception e){root.addView(tv("Historii se nepodařilo načíst.",16,false));}Button imp=secondary("⇩  Importovat sdílený výlet");imp.setOnClickListener(v->importTrip());root.addView(imp);Button b=secondary("Zpět");b.setOnClickListener(v->home());root.addView(b);}
 void historyDetail(int ix){base();try{JSONObject g=new JSONArray(prefs.getString("history","[]")).getJSONObject(ix);title(g.optString("title"),g.optString("date")+" • "+(g.optBoolean("unfinished")?"nedokončeno":"vítěz: "+g.optString("winner")));String note=g.optString("note");if(!note.isEmpty())root.addView(tv(note,17,false));JSONArray ph=g.optJSONArray("photos");if(ph!=null&&ph.length()>0){section("Fotky z výletu");addPhotoGallery(root,ph,240);}Button add=secondary(ph!=null&&ph.length()>0?"📷 Přidat další fotky":"📷 Přidat fotky");add.setEnabled(ph==null||ph.length()<5);add.setOnClickListener(v->editHistoryPhotos(ix));root.addView(add);section("Výsledky");JSONArray ps=g.getJSONArray("players");for(int i=0;i<ps.length();i++){JSONObject p=ps.getJSONObject(i);root.addView(tv(p.getString("name")+": "+num(p.getDouble("score"))+" bodu  •  správně "+p.optInt("correct")+"  •  převzaté "+p.optInt("steals"),17,true));}section("Otázky z výletu");JSONArray qs=g.optJSONArray("questions");for(int i=0;qs!=null&&i<qs.length();i++){JSONObject q=qs.getJSONObject(i);root.addView(tv((i+1)+". "+q.optString("question"),16,true));root.addView(tv("Správně: "+q.getJSONArray("options").optString(q.optInt("correct"))+"\n"+q.optString("explanation"),14,false));}}catch(Exception e){root.addView(tv("Záznam se nepodařilo otevřít.",16,false));}Button sh=btn("Sdílet tento výlet");sh.setOnClickListener(v->shareTrip(ix));root.addView(sh);Button b=secondary("Zpět do kroniky");b.setOnClickListener(v->history());root.addView(b);}
 void editHistoryPhotos(int ix){try{JSONObject g=new JSONArray(prefs.getString("history","[]")).getJSONObject(ix);selectedPhotos.clear();JSONArray ph=g.optJSONArray("photos");for(int i=0;ph!=null&&i<ph.length();i++)selectedPhotos.add(ph.getString(i));pendingPhotoHistoryIndex=ix;pickPhotos();}catch(Exception e){toast("Fotky se nepodařilo otevřít");}}
 void updateHistoryPhotos(int ix){try{JSONArray all=new JSONArray(prefs.getString("history","[]"));all.getJSONObject(ix).put("photos",new JSONArray(selectedPhotos));prefs.edit().putString("history",all.toString()).apply();toast("Fotky byly uložené do kroniky");}catch(Exception e){toast("Fotky se nepodařilo uložit");}}
 void addPhotoGallery(LinearLayout parent,JSONArray photos,int height){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);for(int i=0;i<photos.length();i++){try{ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setImageURI(Uri.parse(photos.getString(i)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,height,1);p.setMargins(4,4,4,4);row.addView(image,p);}catch(Exception ignored){}}parent.addView(row);}
 void shareTrip(int ix){try{JSONObject g=new JSONArray(prefs.getString("history","[]")).getJSONObject(ix);JSONArray ph=g.optJSONArray("photos");ArrayList<Uri> images=new ArrayList<>();for(int j=0;ph!=null&&j<ph.length();j++)try{images.add(Uri.parse(ph.getString(j)));}catch(Exception ignored){}Intent i=new Intent(images.isEmpty()?Intent.ACTION_SEND:Intent.ACTION_SEND_MULTIPLE);i.setType(images.isEmpty()?"text/plain":"image/*");i.putExtra(Intent.EXTRA_SUBJECT,"Výletní kvíz – "+g.optString("title"));i.putExtra(Intent.EXTRA_TEXT,"VYLETNI_KVIZ_2:"+g.toString());if(!images.isEmpty()){i.putParcelableArrayListExtra(Intent.EXTRA_STREAM,images);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);}startActivity(Intent.createChooser(i,"Sdílet vzpomínku na výlet"));}catch(Exception e){toast("Výlet se nepodařilo sdílet");}}
 void importTrip(){final EditText e=edit("Vložte text začínající VYLETNI_KVIZ_2:","");e.setMinLines(5);new AlertDialog.Builder(this).setTitle("Importovat výlet").setMessage("Vložte sem celý text, který vám poslal druhý hráč.").setView(e).setPositiveButton("Importovat",(d,w)->{try{String s=e.getText().toString().trim();if(!s.startsWith("VYLETNI_KVIZ_2:"))throw new Exception();JSONObject g=new JSONObject(s.substring(15));JSONArray old=new JSONArray(prefs.getString("history","[]")),all=new JSONArray();all.put(g);for(int i=0;i<old.length();i++)all.put(old.get(i));prefs.edit().putString("history",all.toString()).apply();toast("Výlet byl přidán do kroniky");history();}catch(Exception ex){toast("Tento sdílený záznam není platný");}}).setNegativeButton("Zrušit",null).show();}
 void stats(){base();title("TABULKA HRÁČŮ","Dlouhodobé výsledky z dokončených výletů.");HashMap<String,Stat> map=new HashMap<>();try{JSONArray a=new JSONArray(prefs.getString("history","[]"));for(int i=0;i<a.length();i++){JSONObject g=a.getJSONObject(i);if(g.optBoolean("unfinished"))continue;JSONArray ps=g.getJSONArray("players");for(int j=0;j<ps.length();j++){JSONObject p=ps.getJSONObject(j);String n=p.getString("name");Stat s=map.get(n);if(s==null){s=new Stat(n);map.put(n,s);}s.games++;s.points+=p.optDouble("score");s.correct+=p.optInt("correct");s.wrong+=p.optInt("wrong");s.steals+=p.optInt("steals");if(Arrays.asList(g.optString("winner").split(" a ")).contains(n))s.wins++;}}}catch(Exception ignored){}ArrayList<Stat> list=new ArrayList<>(map.values());Collections.sort(list,(a,b)->Integer.compare(b.wins,a.wins));if(list.isEmpty())root.addView(tv("Statistiky se objeví po první dokončené hře.",18,false));int rank=1;for(Stat s:list){double hit=s.correct+s.wrong==0?0:100.0*s.correct/(s.correct+s.wrong);root.addView(tv((rank++)+". "+s.name+"  •  "+s.wins+" výher",21,true));root.addView(tv(s.games+" her  •  "+num(s.points)+" bodů  •  úspěšnost "+Math.round(hit)+" %  •  převzaté "+s.steals,15,false));}Button b=btn("Zpět");b.setOnClickListener(v->home());root.addView(b);}

 void connection(){base();title("PŘIPOJENÍ K AI","Klíč je zašifrovaný v tomto telefonu a není součástí aplikace ani GitHubu.");boolean saved=!getSecret().isEmpty();TextView state=tv(saved?"✓ OpenAI klíč je bezpečně uložený":"OpenAI klíč zatím není uložený",17,true);state.setTextColor(saved?GREEN:RED);root.addView(state);EditText t=edit(saved?"Nový klíč (nechte prázdné pro zachování)":"Vložte nový OpenAI API klíč","");t.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);root.addView(t);CheckBox show=check("Zobrazit během zadávání",false);show.setOnCheckedChangeListener((v,on)->{t.setInputType(InputType.TYPE_CLASS_TEXT|(on?InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD:InputType.TYPE_TEXT_VARIATION_PASSWORD));t.setSelection(t.length());});root.addView(show);TextView help=tv("Klíč obvykle začíná sk-. Nikomu ho neposílejte. Spotřeba se účtuje z vašeho kreditu OpenAI.",14,false);root.addView(help);Button s=btn(saved?"Uložit nový klíč":"Uložit klíč");s.setOnClickListener(v->{String value=t.getText().toString().trim();if(value.isEmpty()&&saved){home();return;}if(!value.startsWith("sk-")){toast("To nevypadá jako platný OpenAI klíč");return;}try{setSecret(value);t.setText("");toast("Klíč je bezpečně uložený");home();}catch(Exception e){toast("Klíč se nepodařilo bezpečně uložit");}});root.addView(s);if(saved){Button del=secondary("Odstranit uložený klíč");del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Odstranit klíč?").setMessage("AI generování přestane fungovat, dokud nevložíte nový klíč.").setPositiveButton("Odstranit",(d,w)->{clearSecret();toast("Klíč byl odstraněn");connection();}).setNegativeButton("Zrušit",null).show());root.addView(del);}Button b=secondary("Zpět");b.setOnClickListener(v->home());root.addView(b);}
 void setSecret(String value)throws Exception{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(!ks.containsAlias(KEY_ALIAS)){KeyGenerator kg=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");kg.init(new KeyGenParameterSpec.Builder(KEY_ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());kg.generateKey();}SecretKey key=((KeyStore.SecretKeyEntry)ks.getEntry(KEY_ALIAS,null)).getSecretKey();Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,key);byte[] encrypted=cipher.doFinal(value.getBytes(StandardCharsets.UTF_8));prefs.edit().putString("openai_secret",Base64.encodeToString(encrypted,Base64.NO_WRAP)).putString("openai_iv",Base64.encodeToString(cipher.getIV(),Base64.NO_WRAP)).remove("token").apply();}
 String getSecret(){try{String data=prefs.getString("openai_secret",""),iv=prefs.getString("openai_iv","");if(data.isEmpty()||iv.isEmpty())return "";KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);SecretKey key=((KeyStore.SecretKeyEntry)ks.getEntry(KEY_ALIAS,null)).getSecretKey();Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key,new GCMParameterSpec(128,Base64.decode(iv,Base64.NO_WRAP)));return new String(cipher.doFinal(Base64.decode(data,Base64.NO_WRAP)),StandardCharsets.UTF_8);}catch(Exception e){return "";}}
 void clearSecret(){prefs.edit().remove("openai_secret").remove("openai_iv").apply();try{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(ks.containsAlias(KEY_ALIAS))ks.deleteEntry(KEY_ALIAS);}catch(Exception ignored){}}
 void saveProfiles(){try{JSONArray a=new JSONArray();for(Player p:players)a.put(new JSONObject().put("name",p.name).put("topic",p.topic));prefs.edit().putString("profiles",a.toString()).apply();}catch(Exception ignored){}}
 String[][] profiles(){try{JSONArray a=new JSONArray(prefs.getString("profiles","[]"));String[][] r=new String[a.length()][2];for(int i=0;i<a.length();i++){r[i][0]=a.getJSONObject(i).optString("name");r[i][1]=a.getJSONObject(i).optString("topic");}return r;}catch(Exception e){return new String[0][0];}}
 void trim(int n){while(quiz.size()>n)quiz.remove(quiz.size()-1);}
 void loadAsset(){try{parse(new JSONObject(read(getAssets().open("default_quiz.json"))));}catch(Exception e){toast("Otázky se nepodařilo načíst");}}
 void parse(JSONObject o)throws Exception{quiz.clear();JSONArray a=o.getJSONArray("questions");for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);JSONArray ar=x.getJSONArray("options");String[] opts=new String[4];for(int j=0;j<4;j++)opts[j]=ar.getString(j);quiz.add(new Question(x.getString("question"),opts,x.getInt("correct"),x.getString("explanation"),x.optBoolean("hard")));}}
 String read(InputStream i)throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] x=new byte[4096];int n;while((n=i.read(x))>0)b.write(x,0,n);return b.toString("UTF-8");}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 public void onBackPressed(){home();}

 static class Player{String name,topic;int color;Player(String n,String t,int c){name=n;topic=t;color=c;}}
 static class Question{String text,explanation,special="";String[] options;int correct;boolean hard;Question(String t,String[]o,int c,String e,boolean h){text=t;options=o;correct=c;explanation=e;hard=h;}JSONObject json()throws Exception{return new JSONObject().put("question",text).put("options",new JSONArray(options)).put("correct",correct).put("explanation",explanation).put("hard",hard).put("special",special);}}
 static class Config{String title="Výlet",date="",note="",diff="Vyvážená";int count=40,bizarreEvery=5,strongEvery=3;boolean bizarre=true,strong=true,sound=true,personalized=false;ArrayList<String> cats=new ArrayList<>(),photos=new ArrayList<>();}
 static class State{int index,owner,responder,attempt;double[] scores;int[] correct,wrong,steals;boolean[] blocked=new boolean[4];boolean answered;State(int n){scores=new double[n];correct=new int[n];wrong=new int[n];steals=new int[n];}State copy(){State x=new State(scores.length);x.index=index;x.owner=owner;x.responder=responder;x.attempt=attempt;x.scores=scores.clone();x.correct=correct.clone();x.wrong=wrong.clone();x.steals=steals.clone();x.blocked=blocked.clone();x.answered=answered;return x;}}
 static class Stat{String name;int games,wins,correct,wrong,steals;double points;Stat(String n){name=n;}}
}
